name: Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    name: Linux
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Godot Export
      run: |
        OUTPUT="$(godot --headless --export-release 'Linux' out/release . 2>&1)"
        echo "$OUTPUT"
        if echo "$OUTPUT" |& grep "Cannot export project"
        then
          echo -e "\n\n\nThere was an error found in the Godot export log!"
          exit -1
        fi

  windows:
    name: Windows
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Godot Export
      run: |
        OUTPUT="$(godot --headless --export-release 'Windows' out/release . 2>&1)"
        echo "$OUTPUT"
        if echo "$OUTPUT" |& grep "Cannot export project"
        then
          echo -e "\n\n\nThere was an error found in the Godot export log!"
          exit -1
        fi

  macos:
    name: macOS
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Godot Export
      run: |
        OUTPUT="$(godot --headless --export-release 'macOS' out/release . 2>&1)"
        echo "$OUTPUT"
        if echo "$OUTPUT" |& grep "Cannot export project"
        then
          echo -e "\n\n\nThere was an error found in the Godot export log!"
          exit -1
        fi
