name: Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  export:
    name: Export
    runs-on: self-hosted
    strategy:
      matrix:
        export_name: [
          "Linux_x86_64",
          "Windows_Desktop_x86_64",
          "macOS_Universal"
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Create export folder
      run: |
        mkdir -p 'Builds/${{ matrix.export_name }}'
        chmod a+wrx -R 'Builds/${{ matrix.export_name }}'
        ls -al -R Builds/

    - name: Godot Export
      run: |
        OUTPUT="$(godot --headless --export-release '${{ matrix.export_name }}' 'Builds/${{ matrix.export_name }}' . 2>&1)"
        echo "$OUTPUT"
        if echo "$OUTPUT" |& grep "ERROR: "
        then
          echo -e "\n\n\nThere was an error found in the Godot export log!"
          exit -1
        fi
